<?php

namespace ProcessWire;

class IcsGenerator extends WireData implements Module {

    public static function getModuleInfo() {
        return array(
            'title' => 'ICS Generator',
            'summary' => 'This module can generate ICS files.',
            'author' => 'Timo Hausmann',
            'version' => '210',
            'autoload' => false,
            'requires' => array(
                'PHP>=7.0.0',
                'ProcessWire>=3.0.0',
            ),
            'icon' => 'calendar',
        );
    }

    public function init() {
        require_once(__DIR__ . '/ICS.php');
        $this->set('events', new WireArray());
    }

    /**
     * Returns the ICS object
     * @return \ICSGen\ICS
     */
    public function getICS(): \ICSGen\ICS {
        return new \ICSGen\ICS($this->events);
    }

    /**
     * Returns the ICS file content as a string
     * @return string
     */
    public function getString(): string {
        $ics = $this->getICS();
        return $ics->to_string();
    }

    /**
     * Creates a temporary ProcessWire file and returns it's file path
     * @param string $filename
     * @return string
     * @throws WireException on file write error
     */
    public function getFile($filename = null): string {

        if ($filename === null) {
            $filename = 'ics-' . bin2hex(random_bytes(8)) . '.ics';
        }

        $str = $this->getString();
        $filepath = $this->getTempFilepath($filename);
        $bytes = wire()->files->filePutContents($filepath, $str, LOCK_EX);

        if ($bytes === false) {
            throw new WireException('Failed to write ICS file');
        }

        return $filepath;
    }

    /**
     * Returns a temporary file path
     * @return string
     */
    private function getTempFilepath(string $filename): string {
        $tempDir = wire()->files->tempDir('icsgenerator');
        return $tempDir->get() . $filename;
    }
}
